name = "cek2"
main = "src/index.js"
compatibility_date = "2023-12-01"

# Serve the static HTML frontend
assets = { directory = "./public", binding = "ASSETS" }


[[d1_databases]]
binding = "DB" # i.e. env.DB
database_name = "cek_pembayaran"
database_id = "69ad8ba7-d767-4465-9fa4-766f9c15339f"
